version: '3.9'
services:

  db:
    image: postgres:16.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
    hostname: 'db'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:alpine'
    hostname: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: 'web'
    ports:
      - '8000:8000'
    command: sh -c 'python3 manage.py migrate && python3 manage.py runserver 0:8000 --insecure'
    volumes:
      - static_files:/app/static/
      - media_files:/app/media/
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    hostname: 'celery'
    command: 'python3 -m celery -A config worker -l info'
    depends_on:
    - redis
    - web
    - db

volumes:
  static_files:
  media_files:
  redis_data:
  db_data:
